---
abstract: 'a KiokuDB interface for storing and retrieving '
author:
  - 'Tara L Andrews <aurum@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Memory::Cycle: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Tradition::Directory
name: Text-Tradition-Directory
no_index:
  directory:
    - inc
    - t
requires:
  Class::Load: 0
  DBI: 0
  JSON: 0
  KiokuDB::Backend::DBI: 0
  KiokuDB::GC::Naive: 0
  KiokuDB::TypeMap: 0
  KiokuDB::TypeMap::Entry::Naive: 0
  KiokuX::Model: 0
  KiokuX::User::Util: 0
  Moose: 0
  Moose::Role: 0
  Safe::Isa: 0
  Text::Tradition: 1.1
  TryCatch: 0
  YAML::XS: 0
  namespace::clean: 0
  perl: 5.12.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.1
